[package]
name = "coap-test"
version = "0.1.0"
edition = "2021"

[dependencies]
coap = "0.19"
coap-lite = "0.11.3"
tokio = { version = "^1.32", features = ["full"] }
serde_json = "1.0.132"
serde = { version = "1.0", features = ["derive"] }
